### PR TITLE
Add emacs-25.2

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by DamienCassou** [comment]
I rapidely try to build the travis binary, but failed:

```
[cassou@luz4 travis-cookbooks]$ vagrant init hashicorp/precise64
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
[cassou@luz4 travis-cookbooks]$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'hashicorp/precise64' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'hashicorp/precise64'
    default: URL: https://atlas.hashicorp.com/hashicorp/precise64
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: hashicorp/precise64
Address: https://atlas.hashicorp.com/hashicorp/precise64
Requested provider: [:libvirt]
[cassou@luz4 travis-cookbooks]$ 
```

**Comment by DamienCassou** [comment]
I fixed the build instructions in #85 and did manage to produce an emacs travis tarball. Please change the URL in `recipes/emacs-25.2-travis.rb` before merging.

**Comment by rejeep** [comment]
@DamienCassou Shouldn't the tests pass now that you have hosted the tar yourself?

**Comment by DamienCassou** [comment]
I built the tarball again. Let's see what Travis says about this one.

**Comment by DamienCassou** [comment]
It seems to work better now. The only problem I see is also present in Emacs 25.1 build :
```
Randomized with seed 6059

...............................Failed! See logs above for error...............................................................................

Finished in 0.18023 seconds (files took 0.14398 seconds to load)
```

Can you please put the tarball somewhere else, change the URL and merge that?

**Comment by rejeep** [comment]
I have downloaded the tar, so you can change the URL to https://github.com/rejeep/evm/releases/download/v0.10.0/emacs-25.2-travis.tar.gz and then I'll merge.

**Comment by DamienCassou** [comment]
I changed the URL and updated the PR but now the build doesn't work because there is no file at this URL. I guess you will do that later.

**Comment by rejeep** [comment]
@DamienCassou v0.10.0 is up now, want to try it out?

**Pull request merged**
