### PR TITLE
Simplify building emacs-$VERSION-travis.tar.gz

### PR DESCRIPTION
**Pull request by gonewest818**
This pull request adds some tooling to simplify building new versions of Emacs for use in Travis CI:
- `Dockerfile` encapsulates the setup of the Travis build image
- `build-emacs.sh` automates the steps to download sources and compile
- `generate.sh` is the wrapper you use to compile and export the .tar.gz file

In other words, this makes it so you just type

    $ docker/generate.sh -v 26.0.91

on a machine that has Docker installed and the script takes care of the rest.

Speaking of which, this script makes it possible to generate a new build for the recently posted Emacs 26.0.91, so I updated the recipe and the `.travis.yml` build matrix too.

### CODE REVIEW

**Comment by gonewest818** [comment]
Ah, I see the Travis CI job failed because it specifically checks the major/minor version number against a template where "emacs-26-pretest-travis" and "emacs-git-snapshot-travis" would never match. That will need to be fixed.

**Comment by sambrightman** [comment]
I already have a build for the new 26 ready, but waiting to confirm that the mis-configuration of ELPA is the only thing blocking built-in TLS from working.

**Comment by gonewest818** [comment]
Ok, and it would be easy to back out the gnutls-bin and keep the rest of the docker tooling.

**Comment by gonewest818** [comment]
I rebased this pull request on top of the recent commits to master so that this pull request will merge without modification.  It now incorporates the `--without-x --with-x-toolkit=no --with-gnutls` options in the build automation (`generate.sh` and `build-emacs.sh`) while removing the instructions from `README.md`. With this pull request the user no longer needs to follow a series of steps manually. They can just run the `generate.sh` script.

**Pull request merged**
