### PR TITLE
Fix building Travis binaries instructions

### PR DESCRIPTION
**Pull request by DamienCassou**
I'm not done yet as my build is not finished. Moreover, I encountered the problem documented in http://stackoverflow.com/questions/37544423/how-to-build-emacs-from-source-in-docker-hub-gap-between-bss-and-heap#37561793.

### CODE REVIEW

**Comment by DamienCassou** [comment]
up

**Comment by DamienCassou** [comment]
Up!

**Comment by rejeep** [comment]
up?

**Comment by DamienCassou** [comment]
@rejeep: I meant: "could you please have a look at this PR and give feedback or merge it?". I usually use "up" in the sense "Make this thread to the top of the list again" (as adding a message to a thread typically moves the thread up in forums) :-). Sorry for the confusion.

**Comment by rejeep** [comment]
Ahh, you mean bump! 😄 

Looks good, merging, thanks! 👍

**Pull request merged**
