### PR TITLE
Add emacs-25.3

### PR DESCRIPTION
**Pull request by sambrightman**
I'll edit the commit with the GitHub URL once you have made a release.

There is also a new git snapshot at
https://www.dropbox.com/s/twvkxrtav60rwny/emacs-git-snapshot-travis.tar.gz?dl=1
Note that this is really tip of master, so on the 27.x track. 26 has
already branched.

### CODE REVIEW

**Comment by rejeep** [comment]
Thanks, I downloaded the two tar balls, so you can update the URL (Use the v0.11 release version).

**Comment by sambrightman** [comment]
I've updated the PR.

**Comment by rejeep** [comment]
Can you also update: https://github.com/rejeep/evm/blob/master/recipes/emacs-git-snapshot-travis.rb

**Comment by sambrightman** [comment]
Ah yes, forgot about that. Done now.

**Comment by rejeep** [comment]
Added the tar balls to the release, thanks for contributing! 👍

**Pull request merged**
